# Generated by Django 3.1.7 on 2021-03-23 16:50

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import video_encoding.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('width', models.PositiveIntegerField(editable=False, null=True, verbose_name='Width')),
                ('height', models.PositiveIntegerField(editable=False, null=True, verbose_name='Height')),
                ('duration', models.FloatField(editable=False, null=True, verbose_name='Duration')),
                ('file', video_encoding.fields.VideoField(height_field='height', upload_to='', width_field='width')),
                ('preview', models.ImageField(blank=True, upload_to='', verbose_name='Preview')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Video',
            },
        ),
    ]
